.PHONY: all
# .SILENT:

all:
	$(MAKE) --no-print-directory -C go

test-unit:
	$(MAKE) --no-print-directory -C go test-unit

test:
	$(MAKE) --no-print-directory -C go test

clean:
	$(MAKE) --no-print-directory -C go clean
