.PHONY: all
# .SILENT:

all:
	$(MAKE) --no-print-directory -C service_controller

test-unit:
	$(MAKE) --no-print-directory -C service_controller test-unit

clean:
	$(MAKE) --no-print-directory -C service_controller clean
