%% Sequence Diagram for Deleting a Service Binding

sequenceDiagram
  participant Platform
  participant API  
  participant Service Broker

note over Platform: Delete service binding

Platform ->>+ Service Broker: DELETE /v2/service_instances/:id/service_bindings/:id
Service Broker -->> Platform: {...}