%% Sequence Diagram for Updating a service instance

sequenceDiagram
  participant Platform
  participant API  
  participant Service Broker

note over Platform: Update service instance (synchronously)

Platform ->>+ Service Broker: PATCH /v2/service_instances/:id
Service Broker -->> Platform:{...}

note over Platform: Update service instance (asynchronously)

Platform ->>+ Service Broker: PATCH /v2/service_instances/:id?accepts_incomplete=true

Service Broker -->> Platform:{ “operation”: ... } 

loop Polling last operation

Platform ->>+ Service Broker: GET /v2/service_instances/:instance_id/last_operation
Service Broker ->>+ Service Broker:{ “state”: “in progress” }
Service Broker -->> Platform:{ “state”: “succeeded” }

end



